package com.starturn.database.entities;
// Generated 12-Jan-2020 16:59:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * ContributionFrequency generated by hbm2java
 */
@Entity
@Table(name="contribution_frequency"
    ,catalog="starturn"
)
public class ContributionFrequency  implements java.io.Serializable {


     private int id;
     private Long version;
     private String name;
     private Set targetSavingsPlans = new HashSet(0);
     private Set esusuGroups = new HashSet(0);

    public ContributionFrequency() {
    }

	
    public ContributionFrequency(int id) {
        this.id = id;
    }
    public ContributionFrequency(int id, String name, Set targetSavingsPlans, Set esusuGroups) {
       this.id = id;
       this.name = name;
       this.targetSavingsPlans = targetSavingsPlans;
       this.esusuGroups = esusuGroups;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

    
    @Column(name="name", length=500)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contributionFrequency")
    public Set getTargetSavingsPlans() {
        return this.targetSavingsPlans;
    }
    
    public void setTargetSavingsPlans(Set targetSavingsPlans) {
        this.targetSavingsPlans = targetSavingsPlans;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contributionFrequency")
    public Set getEsusuGroups() {
        return this.esusuGroups;
    }
    
    public void setEsusuGroups(Set esusuGroups) {
        this.esusuGroups = esusuGroups;
    }




}


