package com.starturn.database.entities;
// Generated 12-Jan-2020 16:59:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Requirement generated by hbm2java
 */
@Entity
@Table(name="requirement"
    ,catalog="starturn"
)
public class Requirement  implements java.io.Serializable {


     private int id;
     private Long version;
     private String requirementName;
     private String requirementDescription;
     private String requirementCode;
     private Boolean memberHasAccess;
     private Boolean adminHasAccess;
     private Set requirementGroupAccesses = new HashSet(0);
     private Set userGroupRequirements = new HashSet(0);

    public Requirement() {
    }

	
    public Requirement(int id) {
        this.id = id;
    }
    public Requirement(int id, String requirementName, String requirementDescription, String requirementCode, Boolean memberHasAccess, Boolean adminHasAccess, Set requirementGroupAccesses, Set userGroupRequirements) {
       this.id = id;
       this.requirementName = requirementName;
       this.requirementDescription = requirementDescription;
       this.requirementCode = requirementCode;
       this.memberHasAccess = memberHasAccess;
       this.adminHasAccess = adminHasAccess;
       this.requirementGroupAccesses = requirementGroupAccesses;
       this.userGroupRequirements = userGroupRequirements;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

    
    @Column(name="requirement_name", length=500)
    public String getRequirementName() {
        return this.requirementName;
    }
    
    public void setRequirementName(String requirementName) {
        this.requirementName = requirementName;
    }

    
    @Column(name="requirement_description", length=500)
    public String getRequirementDescription() {
        return this.requirementDescription;
    }
    
    public void setRequirementDescription(String requirementDescription) {
        this.requirementDescription = requirementDescription;
    }

    
    @Column(name="requirement_code", length=500)
    public String getRequirementCode() {
        return this.requirementCode;
    }
    
    public void setRequirementCode(String requirementCode) {
        this.requirementCode = requirementCode;
    }

    
    @Column(name="member_has_access")
    public Boolean getMemberHasAccess() {
        return this.memberHasAccess;
    }
    
    public void setMemberHasAccess(Boolean memberHasAccess) {
        this.memberHasAccess = memberHasAccess;
    }

    
    @Column(name="admin_has_access")
    public Boolean getAdminHasAccess() {
        return this.adminHasAccess;
    }
    
    public void setAdminHasAccess(Boolean adminHasAccess) {
        this.adminHasAccess = adminHasAccess;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="requirement")
    public Set getRequirementGroupAccesses() {
        return this.requirementGroupAccesses;
    }
    
    public void setRequirementGroupAccesses(Set requirementGroupAccesses) {
        this.requirementGroupAccesses = requirementGroupAccesses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="requirement")
    public Set getUserGroupRequirements() {
        return this.userGroupRequirements;
    }
    
    public void setUserGroupRequirements(Set userGroupRequirements) {
        this.userGroupRequirements = userGroupRequirements;
    }




}


