package com.starturn.database.entities;
// Generated 12-Jan-2020 16:59:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * RequirementGroupAccess generated by hbm2java
 */
@Entity
@Table(name="requirement_group_access"
    ,catalog="starturn"
)
public class RequirementGroupAccess  implements java.io.Serializable {


     private int id;
     private Long version;
     private Requirement requirement;
     private RequirementGroup requirementGroup;

    public RequirementGroupAccess() {
    }

    public RequirementGroupAccess(int id, Requirement requirement, RequirementGroup requirementGroup) {
       this.id = id;
       this.requirement = requirement;
       this.requirementGroup = requirementGroup;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="requirement_id", nullable=false)
    public Requirement getRequirement() {
        return this.requirement;
    }
    
    public void setRequirement(Requirement requirement) {
        this.requirement = requirement;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="requirement_group_id", nullable=false)
    public RequirementGroup getRequirementGroup() {
        return this.requirementGroup;
    }
    
    public void setRequirementGroup(RequirementGroup requirementGroup) {
        this.requirementGroup = requirementGroup;
    }




}


