package com.starturn.database.entities;
// Generated 12-Jan-2020 16:59:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * UserGroupRequirement generated by hbm2java
 */
@Entity
@Table(name="user_group_requirement"
    ,catalog="starturn"
)
public class UserGroupRequirement  implements java.io.Serializable {


     private int id;
     private Long version;
     private Requirement requirement;
     private UserGroup userGroup;

    public UserGroupRequirement() {
    }

	
    public UserGroupRequirement(int id, Requirement requirement) {
        this.id = id;
        this.requirement = requirement;
    }
    public UserGroupRequirement(int id, Requirement requirement, UserGroup userGroup) {
       this.id = id;
       this.requirement = requirement;
       this.userGroup = userGroup;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="requirement_id", nullable=false)
    public Requirement getRequirement() {
        return this.requirement;
    }
    
    public void setRequirement(Requirement requirement) {
        this.requirement = requirement;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_group_id")
    public UserGroup getUserGroup() {
        return this.userGroup;
    }
    
    public void setUserGroup(UserGroup userGroup) {
        this.userGroup = userGroup;
    }




}


